//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDNInterest
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FromName { get; set; }
        public string FromEmail { get; set; }
        public string PostedDate { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string PageURL { get; set; }
    }
}
